services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Corelon77/n8n.git
    branch: master
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        valueFromServiceSecret: N8N_USER
      - key: N8N_BASIC_AUTH_PASSWORD
        valueFromServiceSecret: N8N_PASSWORD
